# Generated by Django 5.2.9 on 2026-03-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_carouselslide_customercarerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Transaction ID from Razorpay or other gateways.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of purchase.', max_digits=10),
        ),
    ]
