# Generated by Django 5.2.12 on 2026-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailotp_otpattempt_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone OTP Verification',
                'verbose_name_plural': 'Phone OTP Verifications',
            },
        ),
    ]
